export interface UserConfig {
  latitude: number;
  longitude: number;
  distance_unit: string;
  altitude_unit: string;
  speed_unit: string;
  cycle_interval_sec: number;
  display_mode: string;
  cycle_count: number;
  proximity_focus_enabled: boolean;
  proximity_focus_km: number;
  proximity_focus_layout_id?: number | null;
  layout_rotation_enabled: boolean;
  layout_playlist_ids: number[];
  layout_rotation_interval_sec: number;
  active_layout_id?: number;
  idle_layout_id?: number;
  onboarding_complete: boolean;
  wifi_ssid?: string;
  auto_update: boolean;
  night_mode: boolean;
  night_mode_start?: string;
  night_mode_end?: string;
  sleep_mode: boolean;
  sleep_mode_start?: string;
  sleep_mode_end?: string;
  timezone?: string;
  led_matrix_brightness: number;
  receiver_source: 'local' | 'network';
  network_readsb_host?: string;
  network_readsb_port: number;
}
