import { Aircraft } from '@/types/aircraft';

export const MOCK_AIRCRAFT: Aircraft = {
  hex_code: '7C6B12',
  callsign: 'QFA123',
  registration: 'VH-OJU',
  type_code: 'B744',
  altitude: 34000,
  ground_speed: 450,
  heading: 245,
  distance_km: 12.5,
  distance_display: '12.5 km',
  vertical_rate: 1200,
  operator_icao: 'QFA',
  operator: 'Qantas',
  model: 'Boeing 747-438',
  manufacturer: 'Boeing',
  squawk: '2341',
  bearing: 245,
  latitude: -33.8568,
  longitude: 151.2153,
  last_seen: new Date().toISOString(),
  messages: 42,
  route: 'BNE-SFO',
  origin: 'BNE',
  destination: 'SFO',
};

export const MOCK_AIRCRAFT_FLEET: Aircraft[] = [
  MOCK_AIRCRAFT,
  {
    hex_code: '7C6B13',
    callsign: 'QFA456',
    registration: 'VH-ZNJ',
    type_code: 'B789',
    altitude: 28000,
    ground_speed: 520,
    heading: 310,
    distance_km: 8.2,
    distance_display: '8.2 km',
    vertical_rate: 1800,
    operator_icao: 'QFA',
    operator: 'Qantas',
    model: 'Boeing 787-9',
    manufacturer: 'Boeing',
    squawk: '1200',
    bearing: 310,
    latitude: -33.92,
    longitude: 151.18,
    last_seen: new Date().toISOString(),
    messages: 28,
    route: 'MEL-PER',
    origin: 'MEL',
    destination: 'PER',
  },
  {
    hex_code: 'A0B1C2',
    callsign: 'UAL88',
    registration: 'N38955',
    type_code: 'B77W',
    altitude: 36000,
    ground_speed: 490,
    heading: 195,
    distance_km: 22.7,
    distance_display: '22.7 km',
    vertical_rate: -400,
    operator_icao: 'UAL',
    operator: 'United Airlines',
    model: 'Boeing 777-300ER',
    manufacturer: 'Boeing',
    squawk: '4532',
    bearing: 195,
    latitude: -33.78,
    longitude: 151.25,
    last_seen: new Date().toISOString(),
    messages: 15,
    route: 'SFO-SYD',
    origin: 'SFO',
    destination: 'SYD',
  },
  {
    hex_code: 'C3D4E5',
    callsign: 'BAW15',
    registration: 'G-STBP',
    type_code: 'A35K',
    altitude: 39000,
    ground_speed: 470,
    heading: 120,
    distance_km: 35.1,
    distance_display: '35.1 km',
    vertical_rate: 0,
    operator_icao: 'BAW',
    operator: 'British Airways',
    model: 'Airbus A350-1000',
    manufacturer: 'Airbus',
    squawk: '2101',
    bearing: 120,
    latitude: -33.65,
    longitude: 151.35,
    last_seen: new Date().toISOString(),
    messages: 9,
    route: 'LHR-SIN',
    origin: 'LHR',
    destination: 'SIN',
  },
  {
    hex_code: 'E5F6A7',
    callsign: 'SIA221',
    registration: '9V-SKP',
    type_code: 'A388',
    altitude: 32000,
    ground_speed: 440,
    heading: 85,
    distance_km: 45.8,
    distance_display: '45.8 km',
    vertical_rate: 600,
    operator_icao: 'SIA',
    operator: 'Singapore Airlines',
    model: 'Airbus A380-800',
    manufacturer: 'Airbus',
    squawk: '3301',
    bearing: 85,
    latitude: -33.58,
    longitude: 151.42,
    last_seen: new Date().toISOString(),
    messages: 6,
    route: 'SIN-SYD',
    origin: 'SIN',
    destination: 'SYD',
  },
  {
    hex_code: 'F7A8B9',
    callsign: 'JST456',
    registration: 'VH-VQL',
    type_code: 'A320',
    altitude: 18000,
    ground_speed: 380,
    heading: 275,
    distance_km: 52.3,
    distance_display: '52.3 km',
    vertical_rate: -1200,
    operator_icao: 'JST',
    operator: 'Jetstar',
    model: 'Airbus A320-200',
    manufacturer: 'Airbus',
    squawk: '7712',
    bearing: 275,
    latitude: -33.51,
    longitude: 151.48,
    last_seen: new Date().toISOString(),
    messages: 3,
    route: 'OOL-MEL',
    origin: 'OOL',
    destination: 'MEL',
  },
];
